from typing import Dict, List
from src.api.omdb import OMDbAPI
import time

def film_eslestirmeleri() -> Dict[str, str]:
    return {
        "3 Aptal": "3 Idiots",
        "A Bugs Life": "A Bug's Life",
        "A Good Dinosaur": "The Good Dinosaur",
        "Ailem Robotlara Karşı": "Robots",
        "Alacakaranlık Efsanesi Şafak Vakti Bölüm 1": "The Twilight Saga: Breaking Dawn - Part 1",
        "Alacakaranlık Efsanesi Şafak Vakti Bölüm 2": "The Twilight Saga: Breaking Dawn - Part 2",
        "Aladdin 1992": "Aladdin",
        "Alice Harikalar Diyarında Aynanın İçinde": "Alice Through the Looking Glass",
        "Alis Harikalar Diyarında": "Alice in Wonderland",
        "Alpha ve Omega": "Alpha and Omega",
        "Amelie": "Amélie",
        "Angry Birds": "The Angry Birds Movie",
        "AntMan and the Wasp": "Ant-Man and the Wasp",
        "AntMan and the Wasp Quantumania": "Ant-Man and the Wasp: Quantumania",
        "Asteriks Sihirli İksirin Sırrı": "Asterix: The Secret of the Magic Potion",
        "Asterix Ve Oburix Gorevimiz Kleopatra": "Asterix & Obelix: Mission Cleopatra",
        "Asterix and Obelix Take on Caesar": "Asterix & Obelix Take on Caesar",
        "Asterix and Obelix The Middle Kingdom": "Asterix & Obelix: The Middle Kingdom",
        "Av Mevsimi": "Open Season",
        "Ayı Paddington 2": "Paddington 2",
        "Açlık Oyunları": "The Hunger Games",
        "Açlık Oyunları Alaycı Kuş Bölüm 1": "The Hunger Games: Mockingjay - Part 1",
        "Açlık Oyunları Alaycı Kuş Bölüm 2": "The Hunger Games: Mockingjay - Part 2",
        "Açlık Oyunları Ateşi Yakalamak": "The Hunger Games: Catching Fire",
        "Baba 1": "The Godfather",
        "Babys Day Out": "Baby's Day Out",
        "Baykus Kralligi Efsanesi": "Legend of the Guardians: The Owls of Ga'Hoole",
        "Baywatch Unrated": "Baywatch",
        "Ben Bir Efsaneyim": "I Am Legend",
        "Ben Robot": "I, Robot",
        "Beverly Hills Cop 2": "Beverly Hills Cop II",
        "Beverly Hills Cop 3": "Beverly Hills Cop III",
        "Beyaz Dis": "White Fang",
        "Big 6 Hero": "Big Hero 6",
        "Big Mommas House": "Big Momma's House",
        "Big Mommas House 2": "Big Momma's House 2",
        "Bilal Ozgurlugun Sesi": "Bilal: A New Breed of Hero",
        "Bir Ay Masalı": "A Month of Sundays",
        "Bizim Aile": "Our Family",
        "Buyuk Pudapeste Oteli": "The Grand Budapest Hotel",
        "Buz Devri Bir Yılbaşı Macerası": "Ice Age: A Mammoth Christmas",
        "Carikli Milyoner": "Slumdog Millionaire",
        "Cars Toon": "Cars Toons",
        "Cehennem Melekleri": "Charlie's Angels",
        "Cehennem Melekleri 2": "Charlie's Angels: Full Throttle",
        "Cehennem Melekleri 3": "Charlie's Angels",
        "Cesur Civciv": "Chicken Little",
        "Cindirella": "Cinderella",
        "Cirkin Ordek Yavrusu ile Farecik": "The Ugly Duckling and Me!",
        "Cloudy Meatball": "Cloudy with a Chance of Meatballs",
        "Cloudy Meatball 2": "Cloudy with a Chance of Meatballs 2",
        "Croods 2": "The Croods: A New Age",
        "Cüce Dedektif Şerlok": "Sherlock Gnomes",
        "Daha Hizli Daha Ofkeli": "The Fast and the Furious: Tokyo Drift",
        "Demir Adam 2": "Iron Man 2",
        "Denizin Sarkisi": "Song of the Sea",
        "Despero": "The Tale of Despereaux",
        "Dev Avcisi Jack": "Jack the Giant Slayer",
        "Dont Look Up": "Don't Look Up",
        "Dora Ve Kayıp Altın Şehri": "Dora and the Lost City of Gold",
        "Dünya Muhteşem Bir Gün": "Earth: One Amazing Day",
        "E.T. The Extra Terrestrial": "E.T. the Extra-Terrestrial",
        "Efsane Besli": "The Fantastic Five",
        "Enkanto Sihirli Dünya": "Encanto",
        "Enzo Yağmurda Yarış Sanatı": "Enzo: The Racing Art",
        "Evcil Hayvanların Gizli Yaşamı": "The Secret Life of Pets",
        "Evcil Hayvanların Gizli Yaşamı 2": "The Secret Life of Pets 2",
        "Fant4stik": "Fantastic Four",
        "Fantastik 4 Gümüş Sörfcünün Yükselişi": "Fantastic Four: Rise of the Silver Surfer",
        "Fantastik Canavarlar Grindelwaldın Suçları": "Fantastic Beasts: The Crimes of Grindelwald",
        "Fantastik Dörtlü": "Fantastic Four",
        "Fight Clup": "Fight Club",
        "G I Joe Kobranın Yükselişi": "G.I. Joe: The Rise of Cobra",
        "G I Joe Misilleme": "G.I. Joe: Retaliation",
        "Galaksinin Koruyucuları 2": "Guardians of the Galaxy Vol. 2",
        "Garfield 2": "Garfield: A Tail of Two Kitties",
        "Gelecek Jenarasyon": "Next Gen",
        "Geleceğe Dönüş 1": "Back to the Future",
        "Geleceğe Dönüş 3": "Back to the Future Part III",
        "Gladyatör": "Gladiator",
        "Godfather 2": "The Godfather: Part II",
        "Godfather 3": "The Godfather: Part III",
        "Godzilla Canavarlar Kralı": "Godzilla: King of the Monsters",
        "Godzilla Kong The New Empire": "Godzilla x Kong: The New Empire",
        "Görevimiz Tehlike Yansımalar": "Mission: Impossible - Rogue Nation",
        "Gülen Adam": "The Man Who Laughs",
        "Han Solo Bir Star Wars Hikayesi": "Solo: A Star Wars Story",
        "Harry Potter Chamber Secrets": "Harry Potter and the Chamber of Secrets",
        "Harry Potter ve Azbakan Tutsağı": "Harry Potter and the Prisoner of Azkaban",
        "Harry Potter ve Felsefe Taşı": "Harry Potter and the Sorcerer's Stone",
        "Harry Potter ve Sırlar Odası": "Harry Potter and the Chamber of Secrets",
        "Harry Potter ve Zümrüdüanka Yoldaşlığı": "Harry Potter and the Order of the Phoenix",
        "Hayalet Sürücü 2 İntikam Ateşi": "Ghost Rider: Spirit of Vengeance",
        "Hayat Kitabı": "The Book of Life",
        "Herkül Özgürlük Savaşcısı": "Hercules",
        "Hokkabaz": "The Prestige",
        "Home Alone 5 The Holiday Heist": "Home Alone: The Holiday Heist",
        "Hotel Transilvania 3": "Hotel Transylvania 3: Summer Vacation",
        "Hotel Transilvanya 4": "Hotel Transylvania: Transformania",
        "How To Train Dragon": "How to Train Your Dragon",
        "How To Train Dragon 2": "How to Train Your Dragon 2",
        "How To Train Dragon 3": "How to Train Your Dragon: The Hidden World",
        "Hızl Ve Öfkeli 6": "Fast & Furious 6",
        "Hızlı Ve Ofkeli Tokyo Yarisi": "The Fast and the Furious: Tokyo Drift",
        "Hızlı Ve Öfkeli 5 Rio Soygunu": "Fast Five",
        "Hızlı Ve Öfkeli Hobbs ve Shaw": "Fast & Furious Presents: Hobbs & Shaw",
        "Hızlı ve Öfkeli 7": "Furious 7",
        "Im Legend": "I Am Legend",
        "Ice Age 2": "Ice Age: The Meltdown",
        "Ice Age 3": "Ice Age: Dawn of the Dinosaurs",
        "Ice Age 4": "Ice Age: Continental Drift",
        "Ice Age 5": "Ice Age: Collision Course",
        "In The Hearth of the Sea": "In the Heart of the Sea",
        "Indiana Jones Crystall Skull": "Indiana Jones and the Kingdom of the Crystal Skull",
        "Indiana Jones Son Macera": "Indiana Jones and the Last Crusade",
        "Indiana Jones Ve Kristal Kafatası Kralligi": "Indiana Jones and the Kingdom of the Crystal Skull",
        "Inglourious Basterads": "Inglourious Basterds",
        "Irish Man": "The Irishman",
        "John Wick 2": "John Wick: Chapter 2",
        "John Wick 4": "John Wick: Chapter 4",
        "Jumanji Yeni Seviye": "Jumanji: The Next Level",
        "Jurassic Park 3": "Jurassic Park III",
        "Kadın Kokusu": "Scent of a Woman",
        "Kamcılı Adam": "Whiplash",
        "Kaptan Amerika Kış Askeri": "Captain America: The Winter Soldier",
        "Kaptan Amerika İlk Yenilmez": "Captain America: The First Avenger",
        "Kapıcılar Kralı": "The Janitor",
        "Kara Sovalye": "The Dark Knight",
        "Kara Sovalye Yükseliyor": "The Dark Knight Rises",
        "Karakomik Filmler Deli": "Scary Movie",
        "Karakomik Filmler Emanet": "Scary Movie 2",
        "Karayip Korsanları 1 Siyah İncinin Laneti": "Pirates of the Caribbean: The Curse of the Black Pearl",
        "Karayip Korsanları 2 Ölü Adamın Sandığı": "Pirates of the Caribbean: Dead Man's Chest",
        "Karayip Korsanları 3 Dünyanın Sonu": "Pirates of the Caribbean: At World's End",
        "Karayip Korsanları 4 Gizemli Denizlerde": "Pirates of the Caribbean: On Stranger Tides",
        "Karayip Korsanları 5 Salazarın İntikamı": "Pirates of the Caribbean: Dead Men Tell No Tales",
        "Karlar Ulkesi 2": "Frozen II",
        "Karlar Ülkesi": "Frozen",
        "Karmakarışık": "Inside Out",
        "Kayıp Balık Dori": "Finding Dory",
        "Kayıp Balık Nemo": "Finding Nemo",
        "Kayıp Dünya Jurassic Park": "The Lost World: Jurassic Park",
        "Kibar Feyzo": "Kibar Feyzo",
        "Kikis Delivery Service": "Kiki's Delivery Service",
        "Kill Bill Volume 1": "Kill Bill: Vol. 1",
        "Kingsman Altin Cember": "Kingsman: The Golden Circle",
        "Kingsman Gizli Servis": "Kingsman: The Secret Service",
        "Kirpi Sonic": "Sonic the Hedgehog",
        "Klaus Sihirli Plan": "Klaus",
        "Kolonya Cumhuriyeti": "Kolonya Cumhuriyeti",
        "Kolpaçino 3 Devre": "Kolpaçino 3",
        "Kolpaçino Bir Şehir Efsanesi": "Kolpaçino",
        "Kralın Kılıcı Final Fantasy XV": "Kingsglaive: Final Fantasy XV",
        "Kurtlar Vadisi Gladio": "Valley of the Wolves: Gladio",
        "Kutsal Damacana 2": "Kutsal Damacana 2",
        "Kutsal Hazine Avcilari": "National Treasure",
        "Kuzuların Sessizliği": "The Silence of the Lambs",
        "Küçük Ayaklar": "Smallfoot",
        "Küçük Kahramanlar": "Small Soldiers",
        "Lilo And Stitch": "Lilo & Stitch",
        "Lilo And Stitch 2 Stitch Has A Glitch": "Lilo & Stitch 2: Stitch Has a Glitch",
        "Limitess Unrated": "Limitless",
        "Logan Wolverine": "Logan",
        "Look Who Is Back": "Look Who's Back",
        "Luis Ve Uzaylı Dostları": "Luis and the Aliens",
        "Madagaskar 2": "Madagascar: Escape 2 Africa",
        "Madagaskar 3": "Madagascar 3: Europe's Most Wanted",
        "Madagaskar Penguenleri": "Penguins of Madagascar",
        "Malefiz": "Maleficent",
        "Malefiz Kötülüğün Gücü": "Maleficent: Mistress of Evil",
        "Marslı": "The Martian",
        "Maskeli Beşler Irak": "The Masked Five: Iraq",
        "Maskeli Beşler İntikam Peşinde": "The Masked Five: Revenge",
        "Matrix Devrim": "The Matrix Revolutions",
        "Matrix Yeniden Yüklendi": "The Matrix Resurrections",
        "Maymunlar Cehennemi Baslangic": "Rise of the Planet of the Apes",
        "Maymunlar Cehennemi Başlangıç": "Rise of the Planet of the Apes",
        "Maymunlar Cehennemi Şafak Vakti": "Dawn of the Planet of the Apes",
        "Meg Derinlerdeki Dehşet": "The Meg",
        "Megamind The Doom Syndicate": "Megamind",
        "Monster Univercity": "Monsters University",
        "Mowgli Orman Çocuğu": "Mowgli: Legend of the Jungle",
        "Mr Beans Holiday": "Mr. Bean's Holiday",
        "Mr Peabody and Sherman": "Mr. Peabody & Sherman",
        "Mr and Mrs Smith": "Mr. & Mrs. Smith",
        "Muhteşem Yedili": "The Magnificent Seven",
        "My Fathers Dragon": "My Father's Dragon",
        "Naked Gun 3": "Naked Gun 33⅓: The Final Insult",
        "Nefesini Tut 2": "Don't Breathe 2",
        "Nefret Dolu": "Full of Hate",
        "New Yorkta Beş Minare": "Five Minarets in New York",
        "Ninja Kaplumbağalar": "Teenage Mutant Ninja Turtles",
        "Ninja Kaplumbağalar Gölgelerin İçinden": "Teenage Mutant Ninja Turtles: Out of the Shadows",
        "Noel Gecesi Kabusu": "The Nightmare Before Christmas",
        "Oceans 11": "Ocean's Eleven",
        "Oceans 12": "Ocean's Twelve",
        "Oceans 13": "Ocean's Thirteen",
        "Oflu Hocanin Sifresi 2": "Oflu Hocanin Sifresi 2",
        "Ong Bak 2": "Ong Bak 2",
        "Organize İşler": "Organize İşler",
        "Orman Cetesi": "The Jungle Book",
        "Otel Transilvanya 3 Yaz Tatili": "Hotel Transylvania 3: Summer Vacation",
        "Oyuncak Hikayesi": "Toy Story",
        "Pasifik Savasi": "Pacific Rim",
        "Patron Bebek": "The Boss Baby",
        "Patron Mutlu Son Istiyor": "The Boss Baby: Family Business",
        "Pek Yakında": "Coming Soon",
        "Pete Ve Ejderhası": "Pete's Dragon",
        "Pi Nin Yasami": "Life of Pi",
        "Pokmon Pikachu": "Pokémon: Detective Pikachu",
        "Pokmon The First Movie  Mewtwo Strikes Back": "Pokémon: The First Movie",
        "Pokémon Dedektif Pikachu": "Pokémon: Detective Pikachu",
        "Police Academy 2 Their First Assignment": "Police Academy 2: Their First Assignment",
        "Prenses Ve Kurbaga": "The Princess and the Frog",
        "Rafadan Tayfa Hayrimator": "Rafadan Tayfa: Hayrimator",
        "Ralph ve Internet": "Ralph Breaks the Internet",
        "Rambo 3": "Rambo III",
        "Rambo İlk Kan 2": "Rambo: First Blood Part II",
        "Rampage Büyük Yıkım": "Rampage",
        "Ratatuy": "Ratatouille",
        "Raya Ve Son Ejderha": "Raya and the Last Dragon",
        "Resident Evil Apocalypse Theatrical": "Resident Evil: Apocalypse",
        "Resident Evil Raccoon Şehri": "Resident Evil: Welcome to Raccoon City",
        "Robo Ron": "Ron's Gone Wrong",
        "Robot Ron Bir Sorun Var": "Ron's Gone Wrong",
        "Rocky 2": "Rocky II",
        "Rocky 3": "Rocky III",
        "Rogue One Bir Star Wars Hikayesi": "Rogue One: A Star Wars Story",
        "Rush Hour 1": "Rush Hour",
        "Sahte Kabadayı": "Sahte Kabadayı",
        "Savaş Vadisi": "Valley of the Wolves",
        "Schindlers List": "Schindler's List",
        "Scooby Doo Monsters Unleashed": "Scooby-Doo 2: Monsters Unleashed",
        "ScoobyDoo The Mystery Begins": "Scooby-Doo! The Mystery Begins",
        "ScoobyDoo and the Alien Invaders": "Scooby-Doo and the Alien Invaders",
        "ScoobyDoo on Zombie Island": "Scooby-Doo on Zombie Island",
        "Sea Monster": "The Sea Beast",
        "Secret Life ot Pets": "The Secret Life of Pets",
        "Selvi Boylum Al Yazmalım": "Selvi Boylum Al Yazmalım",
        "Sen Benim Her Şeyimsin": "You Are My Everything",
        "Sessiz Tepe": "Silent Hill",
        "Seven Somurai": "Seven Samurai",
        "Sevgiler Simon": "Love, Simon",
        "Sevginin Gücü": "The Power of Love",
        "Sevimli Canavarlar": "Monsters, Inc.",
        "Sevimli Canavarlar Universitesi": "Monsters University",
        "Sihirbazlar Cetesi": "Now You See Me",
        "Sihirbazlar Çetesi 2": "Now You See Me 2",
        "Simarik": "Spoiled",
        "Sindirella": "Cinderella",
        "Siyah Giyen Adamlar 2": "Men in Black II",
        "Siyah Giyen Adamlar 3": "Men in Black 3",
        "Siyah Giyen Adamlar Global Tehdit": "Men in Black: International",
        "Sonic Hedgehog 2": "Sonic the Hedgehog 2",
        "Sonsuzluk Teorisi": "The Theory of Everything",
        "Sosis Partisi": "Sausage Party",
        "Soğuk Savaş": "Cold War",
        "Space Jam Yeni Efsane": "Space Jam: A New Legacy",
        "Spider Man 2": "Spider-Man 2",
        "Sradan Ask": "Ordinary Love",
        "Star Trek Sonsuzluk": "Star Trek Beyond",
        "Star Wars Last Jedi": "Star Wars: The Last Jedi",
        "Star Wars Skywalker İn Yükselişi": "Star Wars: The Rise of Skywalker",
        "Stop Or My Mom Will Shoot": "Stop! Or My Mom Will Shoot",
        "Suikast": "Assassination",
        "Sumelann Sifresi Temel": "Sumelann Sifresi Temel",
        "Superman Donuyor": "Superman Returns",
        "Surfs Up": "Surf's Up",
        "Suyun Sesi": "The Shape of Water",
        "Sümelanın Şifresi 3 Cünyor Temel": "Sümelanın Şifresi 3 Cünyor Temel",
        "Sümelanın Şifresi Temel": "Sümelanın Şifresi Temel",
        "SüngerBob KarePantolon Firarda": "The SpongeBob Movie: Sponge Out of Water",
        "Tam Gaz": "Full Throttle",
        "Tango And Cash": "Tango & Cash",
        "Tasiyici": "The Transporter",
        "Taşıyıcı Son Hız": "The Transporter Refueled",
        "Ten Ten İn Maceraları": "The Adventures of Tintin",
        "Terminator 2 Mahser Gunu": "Terminator 2: Judgment Day",
        "Terminator 3 Makinelerin Yukselisi": "Terminator 3: Rise of the Machines",
        "Terminator Kurtulus": "Terminator Salvation",
        "Terminatör 5 Yaratılış": "Terminator Genisys",
        "Ternet Ninja": "Teenage Mutant Ninja Turtles",
        "Ternet Ninja 2": "Teenage Mutant Ninja Turtles: Out of the Shadows",
        "Ters Yüz": "Inside Out",
        "The Accidental Spy 2001": "The Accidental Spy",
        "The Boxtrools": "The Boxtrolls",
        "The Croods": "The Croods",
        "The Devils Advocate": "The Devil's Advocate",
        "The Emperors New Groove": "The Emperor's New Groove",
        "The Hitchhikers Guide to the Galaxy": "The Hitchhiker's Guide to the Galaxy",
        "The Hunger Games The Ballad of Songbirds and Snakes": "The Hunger Games: The Ballad of Songbirds & Snakes",
        "The Kings Man": "The King's Man",
        "The Pirates Band of Misfits": "The Pirates! Band of Misfits",
        "The Queens Corgi": "The Queen's Corgi",
        "The Turning Red": "Turning Red",
        "Thor Karanlık Dünya": "Thor: The Dark World",
        "Tremors 2": "Tremors 2: Aftershocks",
        "Truva": "Troy",
        "Ucuz Roman": "Pulp Fiction",
        "Umudumuz Şaban": "Umudumuz Şaban",
        "Uçaklar": "Planes",
        "Uçaklar 2": "Planes: Fire & Rescue",
        "Who Am I Jackie Chan": "Who Am I?",
        "Wild Isles S01E01": "Wild Isles",
        "Wild Isles S01E02": "Wild Isles",
        "Wild Isles S01E03": "Wild Isles",
        "Wild Isles S01E04": "Wild Isles",
        "Wild Isles S01E05": "Wild Isles",
        "Woody Woodpecker Goes Camp": "Woody Woodpecker",
        "WreckIt Ralph": "Wreck-It Ralph",
        "XMen": "X-Men",
        "XMen Apocalypse": "X-Men: Apocalypse",
        "XMen Dark Phoenix": "Dark Phoenix",
        "XMen Days of Future Past": "X-Men: Days of Future Past",
        "XMen The Last Stand": "X-Men: The Last Stand",
        "XMen United": "X2: X-Men United",
        "Yaman Tilki": "Fantastic Mr. Fox",
        "Yapay Oyun Enigma 2014": "The Imitation Game",
        "Yarindan Sonra": "The Day After Tomorrow",
        "Yasam Sifresi": "The Theory of Everything",
        "Yeti": "Abominable",
        "Yeti Efsanesi": "Smallfoot",
        "Yeşil Dev": "The Incredible Hulk",
        "Yeşil Dev 2": "The Incredible Hulk",
        "Yeşil Rehber": "Green Book",
        "Yip Man": "Ip Man",
        "Yip Man 3": "Ip Man 3",
        "Yukari Bak": "Up",
        "Yuruyen Sato": "The Walking Dead",
        "Yuzuklerin Efendisi Kralin Donusu": "The Lord of the Rings: The Return of the King",
        "Yıldız Savaşları Bölüm 1 Gizli Tehlike": "Star Wars: Episode I - The Phantom Menace",
        "Yıldız Savaşları Bölüm 2 Klonların Saldırısı": "Star Wars: Episode II - Attack of the Clones",
        "Yıldız Savaşları Bölüm 3 Sithin İntikamı": "Star Wars: Episode III - Revenge of the Sith",
        "Yıldız Savaşları Bölüm 4 Yeni Bir Umut": "Star Wars: Episode IV - A New Hope",
        "Yıldız Savaşları Bölüm 5 İmparator": "Star Wars: Episode V - The Empire Strikes Back",
        "Yıldız Savaşları Bölüm 6 Jedinin Dönüşü": "Star Wars: Episode VI - Return of the Jedi",
        "Yıldız Savaşları Bölüm 7 Güç Uyanıyor": "Star Wars: Episode VII - The Force Awakens",
        "Zafere Hücum": "Rush",
        "Zamana Karsi": "Race Against Time",
        "Zor Ölüm": "Die Hard",
        "Zor Ölüm 2": "Die Hard 2",
        "Çanakkale Yolun Sonu": "Çanakkale Yolun Sonu",
        "Çelik Adam": "Iron Man",
        "Ölü Gelin": "Corpse Bride",
        "Ölümlü Dünya 2": "World War Z",
        "Örümcek Adam 1": "Spider-Man",
        "Örümcek Adam 2": "Spider-Man 2",
        "Örümcek Adam Evden Uzakta": "Spider-Man: Far From Home",
        "Örümcek Adam Eve Dönüş": "Spider-Man: Homecoming",
        "Örümcek Adam Örümcek Evreninde": "Spider-Man: Into the Spider-Verse",
        "İftarlık Gazoz": "İftarlık Gazoz",
        "İkizler Projesi": "The Twins Project",
        "İlk Kan": "First Blood",
        "İnanilmaz Orumcek Adam 2": "The Amazing Spider-Man 2",
        "İnanılmaz Aile": "The Incredibles",
        "İnanılmaz Aile 2": "Incredibles 2",
        "İnanılmaz Orumcek Adam": "The Amazing Spider-Man",
        "İyi Kötü Ve Çirkin": "The Good, the Bad and the Ugly"
    }

def hibrit_film_adi_cevir(film_adi: str, api: OMDbAPI) -> str:
    eslestirmeler = {
        "6 Super Kahraman": "Big Hero 6",
        "A Takimi": "The A-Team",
        "Ailem Robotlara Karsi": "The Mitchells vs. the Machines",
        "Alvin and the Chipmunks The Chipwrecked": "Alvin and the Chipmunks: Chipwrecked",
        "asterix": "Asterix",
        "Asterix Obelix Take on Caesar": "Asterix & Obelix Take on Caesar",
        "Ata Demirer Tek Kişilik Dev Kadro 2": "",
        "Avatar The Last Airbender S01E01": "Avatar: The Last Airbender S01E01",
        "Avengers Ultron": "Avengers: Age of Ultron",
        "Bad Boys Her Zaman Cilgin": "Bad Boys: Always Crazy",
        "Başka Bir Sen": "",
        "Başlat": "Ready Player One",
        "Celal ile Ceren": "Celal and Ceren",
        "Cennetin Krallığı": "Kingdom of Heaven",
        "Charlies Angels": "Charlie's Angels",
        "DeLorean": "Back to the Future",
        "Demir Adam": "Iron Man",
        "Dogadaki Insan": "Man in Nature",
        "Dogu": "",
        "Dune (1984)": "Dune (1984)",
        "En Son Babalar Duyar S01E15": "",
        "Enzo The Racing Art": "The Art of Racing in the Rain",
        "Everyones Hero": "Everyone's Hero",
        "Everything Theory": "",
        "Final Fantasy XV Kings Sword": "Kingsglaive: Final Fantasy XV",
        "Five Minarets in New York": "Five Minarets in New York",
        "Ford vs Ferrari": "Ford v Ferrari",
        "Full of Hate": "",
        "GI Joe the Rise of Cobra: First Look": "G.I. Joe: The Rise of Cobra",
        "GIJoe": "G.I. Joe",
        "Guardians of Galaxy": "Guardians of the Galaxy",
        "Guardians of Galaxy 2": "Guardians of the Galaxy Vol. 2",
        "Guardians of Galaxy 3": "Guardians of the Galaxy Vol. 3",
        "Guzel Ve Cirkin": "Beauty and the Beast",
        "Harry Potter Deathly Hallow  Part 2": "Harry Potter and the Deathly Hallows: Part 2",
        "Harry Potter Prisoners Azkaban": "Harry Potter and the Prisoner of Azkaban",
        "Hayat Bilgisi": "",
        "Iftarlik Gazoz": "Iftarlik Gazoz",
        "Jumanji Forest": "Jumanji: Welcome to the Jungle",
        "Jumanji New Level": "Jumanji: The Next Level",
        "Jumanji Vahi Orman": "Jumanji: Welcome to the Jungle",
        "Kara Panter": "Black Panther",
        "Kibar Feyzo": "Kibar Feyzo",
        "Kingsman": "Kingsman: The Secret Service",
        "Kolonya Cumhuriyeti": "Kolonya Cumhuriyeti",
        "Kurtlar Vadisi Pusu": "Valley of the Wolves: Ambush",
        "Kutsal Damacana 2": "Kutsal Damacana 2: İtmen",
        "E! Online Live from the Red Carpet Men in Black 3": "Men in Black 3",
        "Muhteem Yedili": "",
        "Naked Gun 3 The Final Insult": "Naked Gun 33⅓: The Final Insult",
        "Oflu Hocanin Sifresi 2": "Oflu Hoca'nın Şifresi 2",
        "Organize İşler": "Magic Carpet Ride",
        "Pokemon: Detective Pikachu (2019)": "Pokémon Detective Pikachu",
        "Prens S01E01": "",
        "Rafadan Tayfa: Hayrimator": "Rafadan Tayfa: Hayrimator",
        "Rons Gone Wrong": "Ron's Gone Wrong",
        "Sahte Kabadayı": "Sahte Kabadayı",
        "Savas Vadisi": "Hacksaw Ridge",
        "Selvi Boylum Al Yazmalım": "The Girl with the Red Scarf",
        "Sonic Hedgehog": "Sonic the Hedgehog",
        "Spoiled": "",
        "Sumelann Sifresi Temel": "Sümelanın Şifresi: Temel",
        "Sümelanın Şifresi 3 Cünyor Temel": "Sümelanın Şifresi 3: Cünyor Temel",
        "Sümelanın Şifresi Temel": "Sümelanın Şifresi: Temel",
        "The Fantastic Five": "Fantastic Five",
        "The Planets S01E01": "The Planets S01E01",
        "The Power of Love": "The Power of Love",
        "The Twins Project": "The Twins Project",
        "Tremors 2: Aftershocks": "Tremors 2: Aftershocks",
        "Tuts Treasures Hidden Secrets S01E02": "Tut's Treasures: Hidden Secrets S01E02",
        "Umudumuz Şaban": "Our Hope Şaban",
        "Wreck It Ralph Internet": "Ralph Breaks the Internet",
        "Yenilmezler Sonsuzluk Savasi": "Avengers: Infinity War",
        "You Are My Everything": "You Are My Everything",
        "Çanakkale Yolun Sonu": "Çanakkale: End of the Road",
        "İftarlık Gazoz": "Iftarlik Gazoz",
    }

    if film_adi in eslestirmeler and eslestirmeler[film_adi]:
        return eslestirmeler[film_adi]

    try:
        return api.film_adi_cevir(film_adi)
    except Exception as e:
        print(f"API hatası: {e}")
        return film_adi

if __name__ == "__main__":
    api = OMDbAPI('1d794710')
    eslestirmeler = film_eslestirmeleri()
    with open('FilmList.txt', 'r', encoding='utf-8') as f:
        filmler = [line.strip() for line in f if line.strip()]
    ceviriler = {}
    for film in filmler:
        ceviriler[film] = hibrit_film_adi_cevir(film, api)
        print(f"{film} -> {ceviriler[film]}")
        time.sleep(1)
    with open('film_cevirileri.txt', 'w', encoding='utf-8') as f:
        for turkce, ingilizce in ceviriler.items():
            f.write(f"{turkce} -> {ingilizce}\n") 